"""phase2 internal flow

Revision ID: 26a46bbad8dd
Revises: 3abe576084bc
Create Date: 2026-07-12 12:36:53.806840
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '26a46bbad8dd'
down_revision = '3abe576084bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restock_fold_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folded_through', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restock_fold_state'))
    )
    op.create_table('restock_accum',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('accumulated', sa.Float(), nullable=False),
    sa.Column('last_flagged_on', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_restock_accum_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_restock_accum'))
    )
    op.create_table('restock_checkoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('list_type', sa.String(length=10), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('checked_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checked_by_id'], ['users.id'], name=op.f('fk_restock_checkoffs_checked_by_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_restock_checkoffs_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restock_checkoffs')),
    sa.UniqueConstraint('day', 'list_type', 'product_id', name='uq_restock_checkoff')
    )
    op.create_index(op.f('ix_restock_checkoffs_day'), 'restock_checkoffs', ['day'], unique=False)
    op.create_table('restock_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_type', sa.String(length=10), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('flagged_on', sa.Date(), nullable=False),
    sa.Column('checked_off_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_off_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checked_off_by_id'], ['users.id'], name=op.f('fk_restock_lines_checked_off_by_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_restock_lines_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restock_lines'))
    )
    op.create_index(op.f('ix_restock_lines_list_type'), 'restock_lines', ['list_type'], unique=False)
    op.create_index(op.f('ix_restock_lines_product_id'), 'restock_lines', ['product_id'], unique=False)
    op.create_table('sales_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sales_daily_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_daily')),
    sa.UniqueConstraint('product_id', 'day', 'channel', name='uq_sales_daily_bucket')
    )
    op.create_index(op.f('ix_sales_daily_day'), 'sales_daily', ['day'], unique=False)
    op.create_index(op.f('ix_sales_daily_product_id'), 'sales_daily', ['product_id'], unique=False)
    op.create_table('transfer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_transfer_requests_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_requests'))
    )
    op.create_index(op.f('ix_transfer_requests_status'), 'transfer_requests', ['status'], unique=False)
    op.create_table('order_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('cloned_from_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_note', sa.Text(), nullable=False),
    sa.Column('write_status', sa.String(length=12), nullable=False),
    sa.Column('write_reference', sa.String(length=40), nullable=False),
    sa.Column('write_dry_run_reason', sa.String(length=30), nullable=False),
    sa.Column('write_error', sa.Text(), nullable=False),
    sa.Column('odoo_picking_id', sa.Integer(), nullable=True),
    sa.Column('odoo_picking_name', sa.String(length=80), nullable=False),
    sa.Column('odoo_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_order_lists_approved_by_id_users')),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], name=op.f('fk_order_lists_center_id_centers')),
    sa.ForeignKeyConstraint(['cloned_from_id'], ['order_lists.id'], name=op.f('fk_order_lists_cloned_from_id_order_lists')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_order_lists_created_by_id_users')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_order_lists_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_lists'))
    )
    op.create_index(op.f('ix_order_lists_center_id'), 'order_lists', ['center_id'], unique=False)
    op.create_index(op.f('ix_order_lists_status'), 'order_lists', ['status'], unique=False)
    op.create_index(op.f('ix_order_lists_zone_id'), 'order_lists', ['zone_id'], unique=False)
    op.create_table('transfer_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_transfer_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['request_id'], ['transfer_requests.id'], name=op.f('fk_transfer_events_request_id_transfer_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_events'))
    )
    op.create_index(op.f('ix_transfer_events_request_id'), 'transfer_events', ['request_id'], unique=False)
    op.create_table('transfer_odoo_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('leg', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('dry_run_reason', sa.String(length=30), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('odoo_picking_id', sa.Integer(), nullable=True),
    sa.Column('odoo_picking_name', sa.String(length=80), nullable=False),
    sa.Column('odoo_url', sa.String(length=500), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_transfer_odoo_drafts_created_by_id_users')),
    sa.ForeignKeyConstraint(['request_id'], ['transfer_requests.id'], name=op.f('fk_transfer_odoo_drafts_request_id_transfer_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_odoo_drafts'))
    )
    op.create_index(op.f('ix_transfer_odoo_drafts_request_id'), 'transfer_odoo_drafts', ['request_id'], unique=False)
    op.create_table('transfer_request_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_requested', sa.Float(), nullable=False),
    sa.Column('qty_sent', sa.Float(), nullable=True),
    sa.Column('qty_counted', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_transfer_request_lines_product_id_products')),
    sa.ForeignKeyConstraint(['request_id'], ['transfer_requests.id'], name=op.f('fk_transfer_request_lines_request_id_transfer_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_request_lines')),
    sa.UniqueConstraint('request_id', 'product_id', name='uq_transferreq_product')
    )
    op.create_index(op.f('ix_transfer_request_lines_request_id'), 'transfer_request_lines', ['request_id'], unique=False)
    op.create_table('adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_expected', sa.Float(), nullable=False),
    sa.Column('qty_counted', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['transfer_request_lines.id'], name=op.f('fk_adjustments_line_id_transfer_request_lines')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_adjustments_product_id_products')),
    sa.ForeignKeyConstraint(['request_id'], ['transfer_requests.id'], name=op.f('fk_adjustments_request_id_transfer_requests')),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_adjustments_resolved_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adjustments'))
    )
    op.create_index(op.f('ix_adjustments_request_id'), 'adjustments', ['request_id'], unique=False)
    op.create_index(op.f('ix_adjustments_status'), 'adjustments', ['status'], unique=False)
    op.create_table('order_list_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_list_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_list_id'], ['order_lists.id'], name=op.f('fk_order_list_lines_order_list_id_order_lists')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_list_lines_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_list_lines')),
    sa.UniqueConstraint('order_list_id', 'product_id', name='uq_orderlist_product')
    )
    op.create_index(op.f('ix_order_list_lines_order_list_id'), 'order_list_lines', ['order_list_id'], unique=False)
    op.add_column('centers', sa.Column('odoo_location_id', sa.Integer(), nullable=True))
    # server_default so the ALTER succeeds on an already-populated centers table
    op.add_column('centers', sa.Column('odoo_location_name', sa.String(length=255),
                                       nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('centers', 'odoo_location_name')
    op.drop_column('centers', 'odoo_location_id')
    op.drop_index(op.f('ix_order_list_lines_order_list_id'), table_name='order_list_lines')
    op.drop_table('order_list_lines')
    op.drop_index(op.f('ix_adjustments_status'), table_name='adjustments')
    op.drop_index(op.f('ix_adjustments_request_id'), table_name='adjustments')
    op.drop_table('adjustments')
    op.drop_index(op.f('ix_transfer_request_lines_request_id'), table_name='transfer_request_lines')
    op.drop_table('transfer_request_lines')
    op.drop_index(op.f('ix_transfer_odoo_drafts_request_id'), table_name='transfer_odoo_drafts')
    op.drop_table('transfer_odoo_drafts')
    op.drop_index(op.f('ix_transfer_events_request_id'), table_name='transfer_events')
    op.drop_table('transfer_events')
    op.drop_index(op.f('ix_order_lists_zone_id'), table_name='order_lists')
    op.drop_index(op.f('ix_order_lists_status'), table_name='order_lists')
    op.drop_index(op.f('ix_order_lists_center_id'), table_name='order_lists')
    op.drop_table('order_lists')
    op.drop_index(op.f('ix_transfer_requests_status'), table_name='transfer_requests')
    op.drop_table('transfer_requests')
    op.drop_index(op.f('ix_sales_daily_product_id'), table_name='sales_daily')
    op.drop_index(op.f('ix_sales_daily_day'), table_name='sales_daily')
    op.drop_table('sales_daily')
    op.drop_index(op.f('ix_restock_lines_product_id'), table_name='restock_lines')
    op.drop_index(op.f('ix_restock_lines_list_type'), table_name='restock_lines')
    op.drop_table('restock_lines')
    op.drop_index(op.f('ix_restock_checkoffs_day'), table_name='restock_checkoffs')
    op.drop_table('restock_checkoffs')
    op.drop_table('restock_accum')
    op.drop_table('restock_fold_state')
    # ### end Alembic commands ###
