"""foundation

Revision ID: 3abe576084bc
Revises: 
Create Date: 2026-07-10 10:07:58.004238
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '3abe576084bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odoo_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('complete_name', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odoo_locations')),
    sa.UniqueConstraint('odoo_id', name=op.f('uq_odoo_locations_odoo_id'))
    )
    op.create_index(op.f('ix_odoo_locations_key'), 'odoo_locations', ['key'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('global_sku', sa.String(length=64), nullable=False),
    sa.Column('us_sku', sa.String(length=64), nullable=False),
    sa.Column('odoo_product_id', sa.Integer(), nullable=True),
    sa.Column('odoo_internal_ref', sa.String(length=64), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('retail_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('origin_country', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('is_stock_tracked', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('case_size', sa.Integer(), nullable=False),
    sa.Column('dept_orderable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('odoo_product_id', name=op.f('uq_products_odoo_product_id'))
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_global_sku'), 'products', ['global_sku'], unique=True)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_us_sku'), 'products', ['us_sku'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    op.create_index(op.f('ix_sync_runs_domain'), 'sync_runs', ['domain'], unique=False)
    op.create_table('sync_state',
    sa.Column('domain', sa.String(length=20), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('auth_failed', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('domain', name=op.f('pk_sync_state'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auth_uid', sa.String(length=64), nullable=True),
    sa.Column('invited_by_id', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('email IS NOT NULL OR phone IS NOT NULL', name=op.f('ck_users_email_or_phone_present')),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], name=op.f('fk_users_invited_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('auth_uid', name=op.f('uq_users_auth_uid')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('sheet_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones')),
    sa.UniqueConstraint('name', name=op.f('uq_zones_name'))
    )
    op.create_table('centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activity_raw', sa.String(length=40), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('stripe_terminal_name', sa.String(length=120), nullable=False),
    sa.Column('stripe_terminal_serial', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('shared_product_group', sa.String(length=80), nullable=True),
    sa.Column('needs_followup', sa.Boolean(), nullable=False),
    sa.Column('followup_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_centers_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_centers')),
    sa.UniqueConstraint('name', name=op.f('uq_centers_name'))
    )
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_feature_flags_updated_by_id_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_feature_flags'))
    )
    op.create_table('incoming_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odoo_move_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('picking_ref', sa.String(length=120), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_incoming_moves_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incoming_moves'))
    )
    op.create_index(op.f('ix_incoming_moves_odoo_move_id'), 'incoming_moves', ['odoo_move_id'], unique=False)
    op.create_index(op.f('ix_incoming_moves_product_id'), 'incoming_moves', ['product_id'], unique=False)
    op.create_table('login_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_codes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_codes'))
    )
    op.create_table('odoo_write_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=60), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('dry_run_reason', sa.String(length=60), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('odoo_model', sa.String(length=60), nullable=False),
    sa.Column('odoo_record_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('request_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_odoo_write_audit_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odoo_write_audit'))
    )
    op.create_index(op.f('ix_odoo_write_audit_operation'), 'odoo_write_audit', ['operation'], unique=False)
    op.create_index(op.f('ix_odoo_write_audit_reference'), 'odoo_write_audit', ['reference'], unique=False)
    op.create_table('product_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=30), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_tags_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_tags')),
    sa.UniqueConstraint('product_id', 'tag', name='uq_product_tag')
    )
    op.create_index(op.f('ix_product_tags_product_id'), 'product_tags', ['product_id'], unique=False)
    op.create_table('sales_monthly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sales_monthly_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_monthly')),
    sa.UniqueConstraint('product_id', 'year', 'month', 'channel', name='uq_sales_bucket')
    )
    op.create_index(op.f('ix_sales_monthly_product_id'), 'sales_monthly', ['product_id'], unique=False)
    op.create_table('stock_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_key', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_levels_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_levels')),
    sa.UniqueConstraint('product_id', 'location_key', name='uq_stock_product_location')
    )
    op.create_index(op.f('ix_stock_levels_product_id'), 'stock_levels', ['product_id'], unique=False)
    op.create_table('center_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('role_note', sa.String(length=160), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], name=op.f('fk_center_contacts_center_id_centers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_center_contacts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_center_contacts'))
    )
    op.create_table('role_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('center_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], name=op.f('fk_role_assignments_center_id_centers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_role_assignments_user_id_users')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_role_assignments_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_assignments')),
    sa.UniqueConstraint('user_id', 'role', 'zone_id', 'center_id', name='uq_role_scope')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_assignments')
    op.drop_table('center_contacts')
    op.drop_index(op.f('ix_stock_levels_product_id'), table_name='stock_levels')
    op.drop_table('stock_levels')
    op.drop_index(op.f('ix_sales_monthly_product_id'), table_name='sales_monthly')
    op.drop_table('sales_monthly')
    op.drop_index(op.f('ix_product_tags_product_id'), table_name='product_tags')
    op.drop_table('product_tags')
    op.drop_index(op.f('ix_odoo_write_audit_reference'), table_name='odoo_write_audit')
    op.drop_index(op.f('ix_odoo_write_audit_operation'), table_name='odoo_write_audit')
    op.drop_table('odoo_write_audit')
    op.drop_table('login_codes')
    op.drop_index(op.f('ix_incoming_moves_product_id'), table_name='incoming_moves')
    op.drop_index(op.f('ix_incoming_moves_odoo_move_id'), table_name='incoming_moves')
    op.drop_table('incoming_moves')
    op.drop_table('feature_flags')
    op.drop_table('centers')
    op.drop_table('zones')
    op.drop_table('users')
    op.drop_table('sync_state')
    op.drop_index(op.f('ix_sync_runs_domain'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_products_us_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_global_sku'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_odoo_locations_key'), table_name='odoo_locations')
    op.drop_table('odoo_locations')
    # ### end Alembic commands ###
