"""order list catalogs + odoo native transfers + restock exclude

Revision ID: 85a3b2fdc379
Revises: 26a46bbad8dd
Create Date: 2026-07-12 16:12:49.797769
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '85a3b2fdc379'
down_revision = '26a46bbad8dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Order lists become catalogs and transfer requests become Odoo-native:
    # the old rows carry semantics (quantities, approval state, leg drafts)
    # that no longer exist. Everything here is phase-2 demo data — reset it
    # (children first) and reseed.
    for table in (
        "adjustments",
        "transfer_odoo_drafts",  # dropped below, but its FKs block the deletes
        "transfer_events",
        "transfer_request_lines",
        "transfer_requests",
        "order_list_lines",
        "order_lists",
    ):
        op.execute(f"DELETE FROM {table}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_list_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_list_id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('granted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], name=op.f('fk_order_list_centers_center_id_centers')),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], name=op.f('fk_order_list_centers_granted_by_id_users')),
    sa.ForeignKeyConstraint(['order_list_id'], ['order_lists.id'], name=op.f('fk_order_list_centers_order_list_id_order_lists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_list_centers')),
    sa.UniqueConstraint('order_list_id', 'center_id', name='uq_orderlist_center')
    )
    op.create_index(op.f('ix_order_list_centers_center_id'), 'order_list_centers', ['center_id'], unique=False)
    op.create_index(op.f('ix_order_list_centers_order_list_id'), 'order_list_centers', ['order_list_id'], unique=False)
    op.create_table('order_list_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_list_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('granted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], name=op.f('fk_order_list_zones_granted_by_id_users')),
    sa.ForeignKeyConstraint(['order_list_id'], ['order_lists.id'], name=op.f('fk_order_list_zones_order_list_id_order_lists')),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_order_list_zones_zone_id_zones')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_list_zones')),
    sa.UniqueConstraint('order_list_id', 'zone_id', name='uq_orderlist_zone')
    )
    op.create_index(op.f('ix_order_list_zones_order_list_id'), 'order_list_zones', ['order_list_id'], unique=False)
    op.create_index(op.f('ix_order_list_zones_zone_id'), 'order_list_zones', ['zone_id'], unique=False)
    op.drop_index(op.f('ix_transfer_odoo_drafts_request_id'), table_name='transfer_odoo_drafts')
    op.drop_table('transfer_odoo_drafts')
    op.drop_column('order_list_lines', 'qty')
    op.add_column('order_lists', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_index(op.f('ix_order_lists_center_id'), table_name='order_lists')
    op.drop_index(op.f('ix_order_lists_status'), table_name='order_lists')
    op.drop_index(op.f('ix_order_lists_zone_id'), table_name='order_lists')
    op.drop_constraint(op.f('fk_order_lists_zone_id_zones'), 'order_lists', type_='foreignkey')
    op.drop_constraint(op.f('fk_order_lists_center_id_centers'), 'order_lists', type_='foreignkey')
    op.drop_constraint(op.f('fk_order_lists_approved_by_id_users'), 'order_lists', type_='foreignkey')
    op.drop_column('order_lists', 'assigned_at')
    op.drop_column('order_lists', 'zone_id')
    op.drop_column('order_lists', 'odoo_picking_id')
    op.drop_column('order_lists', 'approved_at')
    op.drop_column('order_lists', 'write_status')
    op.drop_column('order_lists', 'approved_by_id')
    op.drop_column('order_lists', 'write_dry_run_reason')
    op.drop_column('order_lists', 'odoo_url')
    op.drop_column('order_lists', 'center_id')
    op.drop_column('order_lists', 'status')
    op.drop_column('order_lists', 'returned_note')
    op.drop_column('order_lists', 'write_reference')
    op.drop_column('order_lists', 'odoo_picking_name')
    op.drop_column('order_lists', 'write_error')
    op.add_column('products', sa.Column('restock_exclude', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('transfer_requests', sa.Column('picking_status', sa.String(length=12), nullable=False, server_default='none'))
    op.add_column('transfer_requests', sa.Column('picking_reference', sa.String(length=40), nullable=False, server_default=''))
    op.add_column('transfer_requests', sa.Column('picking_error', sa.Text(), nullable=False, server_default=''))
    op.add_column('transfer_requests', sa.Column('odoo_picking_id', sa.Integer(), nullable=True))
    op.add_column('transfer_requests', sa.Column('odoo_picking_name', sa.String(length=80), nullable=False, server_default=''))
    op.add_column('transfer_requests', sa.Column('odoo_picking_url', sa.String(length=500), nullable=False, server_default=''))
    op.add_column('transfer_requests', sa.Column('count_status', sa.String(length=12), nullable=False, server_default='none'))
    op.add_column('transfer_requests', sa.Column('count_reference', sa.String(length=40), nullable=False, server_default=''))
    op.add_column('transfer_requests', sa.Column('count_error', sa.Text(), nullable=False, server_default=''))
    op.add_column('transfer_requests', sa.Column('count_picking_id', sa.Integer(), nullable=True))
    op.add_column('transfer_requests', sa.Column('count_picking_name', sa.String(length=80), nullable=False, server_default=''))
    op.add_column('transfer_requests', sa.Column('count_picking_url', sa.String(length=500), nullable=False, server_default=''))
    op.add_column('transfer_requests', sa.Column('count_barcode_url', sa.String(length=500), nullable=False, server_default=''))
    op.add_column('transfer_requests', sa.Column('count_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_requests', 'count_checked_at')
    op.drop_column('transfer_requests', 'count_barcode_url')
    op.drop_column('transfer_requests', 'count_picking_url')
    op.drop_column('transfer_requests', 'count_picking_name')
    op.drop_column('transfer_requests', 'count_picking_id')
    op.drop_column('transfer_requests', 'count_error')
    op.drop_column('transfer_requests', 'count_reference')
    op.drop_column('transfer_requests', 'count_status')
    op.drop_column('transfer_requests', 'odoo_picking_url')
    op.drop_column('transfer_requests', 'odoo_picking_name')
    op.drop_column('transfer_requests', 'odoo_picking_id')
    op.drop_column('transfer_requests', 'picking_error')
    op.drop_column('transfer_requests', 'picking_reference')
    op.drop_column('transfer_requests', 'picking_status')
    op.drop_column('products', 'restock_exclude')
    op.add_column('order_lists', sa.Column('write_error', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('order_lists', sa.Column('odoo_picking_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('order_lists', sa.Column('write_reference', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('order_lists', sa.Column('returned_note', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('order_lists', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('order_lists', sa.Column('center_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order_lists', sa.Column('odoo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('order_lists', sa.Column('write_dry_run_reason', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('order_lists', sa.Column('approved_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order_lists', sa.Column('write_status', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.add_column('order_lists', sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('order_lists', sa.Column('odoo_picking_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order_lists', sa.Column('zone_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order_lists', sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_order_lists_approved_by_id_users'), 'order_lists', 'users', ['approved_by_id'], ['id'])
    op.create_foreign_key(op.f('fk_order_lists_center_id_centers'), 'order_lists', 'centers', ['center_id'], ['id'])
    op.create_foreign_key(op.f('fk_order_lists_zone_id_zones'), 'order_lists', 'zones', ['zone_id'], ['id'])
    op.create_index(op.f('ix_order_lists_zone_id'), 'order_lists', ['zone_id'], unique=False)
    op.create_index(op.f('ix_order_lists_status'), 'order_lists', ['status'], unique=False)
    op.create_index(op.f('ix_order_lists_center_id'), 'order_lists', ['center_id'], unique=False)
    op.drop_column('order_lists', 'is_archived')
    op.add_column('order_list_lines', sa.Column('qty', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.create_table('transfer_odoo_drafts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leg', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('dry_run_reason', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('odoo_picking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('odoo_picking_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('odoo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_transfer_odoo_drafts_created_by_id_users')),
    sa.ForeignKeyConstraint(['request_id'], ['transfer_requests.id'], name=op.f('fk_transfer_odoo_drafts_request_id_transfer_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_odoo_drafts'))
    )
    op.create_index(op.f('ix_transfer_odoo_drafts_request_id'), 'transfer_odoo_drafts', ['request_id'], unique=False)
    op.drop_index(op.f('ix_order_list_zones_zone_id'), table_name='order_list_zones')
    op.drop_index(op.f('ix_order_list_zones_order_list_id'), table_name='order_list_zones')
    op.drop_table('order_list_zones')
    op.drop_index(op.f('ix_order_list_centers_order_list_id'), table_name='order_list_centers')
    op.drop_index(op.f('ix_order_list_centers_center_id'), table_name='order_list_centers')
    op.drop_table('order_list_centers')
    # ### end Alembic commands ###
