"""phase4 purchase ordering and action tracking

Revision ID: b8539cb5b38a
Revises: fbf52b4d8d4c
Create Date: 2026-07-14 21:44:02.345423
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = 'b8539cb5b38a'
down_revision = 'fbf52b4d8d4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('cc_emails', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors')),
    sa.UniqueConstraint('name', name=op.f('uq_vendors_name'))
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_app_settings_updated_by_id_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('rules_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_source', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('placed_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_purchase_orders_created_by_id_users')),
    sa.ForeignKeyConstraint(['placed_by_id'], ['users.id'], name=op.f('fk_purchase_orders_placed_by_id_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_purchase_orders_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('reference', name=op.f('uq_purchase_orders_reference'))
    )
    op.create_index(op.f('ix_purchase_orders_name'), 'purchase_orders', ['name'], unique=False)
    op.create_index(op.f('ix_purchase_orders_status'), 'purchase_orders', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('forecast_analogies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('analog_product_id', sa.Integer(), nullable=True),
    sa.Column('monthly_estimate', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('graduated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analog_product_id'], ['products.id'], name=op.f('fk_forecast_analogies_analog_product_id_products')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_forecast_analogies_created_by_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_forecast_analogies_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_analogies')),
    sa.UniqueConstraint('product_id', name=op.f('uq_forecast_analogies_product_id'))
    )
    op.create_table('order_email_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('recipients', sa.String(length=500), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], name=op.f('fk_order_email_messages_order_id_purchase_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_email_messages'))
    )
    op.create_index(op.f('ix_order_email_messages_message_id'), 'order_email_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_order_email_messages_order_id'), 'order_email_messages', ['order_id'], unique=False)
    op.create_table('purchase_order_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('method', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('line_quantities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_legs_order_id_purchase_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_legs'))
    )
    op.create_index(op.f('ix_purchase_order_legs_order_id'), 'purchase_order_legs', ['order_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('global_sku', sa.String(length=64), nullable=False),
    sa.Column('suggested_sea_qty', sa.Integer(), nullable=False),
    sa.Column('suggested_air_qty', sa.Integer(), nullable=False),
    sa.Column('baseline_sea_qty', sa.Integer(), nullable=False),
    sa.Column('baseline_air_qty', sa.Integer(), nullable=False),
    sa.Column('origin_sea_qty', sa.Integer(), nullable=False),
    sa.Column('origin_air_qty', sa.Integer(), nullable=False),
    sa.Column('final_sea_qty', sa.Integer(), nullable=False),
    sa.Column('final_air_qty', sa.Integer(), nullable=False),
    sa.Column('line_status', sa.String(length=14), nullable=False),
    sa.Column('substitute_sku', sa.String(length=64), nullable=False),
    sa.Column('target_moh_used', sa.Float(), nullable=False),
    sa.Column('case_size', sa.Integer(), nullable=False),
    sa.Column('suggestion_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_lines_order_id_purchase_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_order_lines_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_lines')),
    sa.UniqueConstraint('order_id', 'global_sku', name='uq_po_line_sku')
    )
    op.create_index(op.f('ix_purchase_order_lines_global_sku'), 'purchase_order_lines', ['global_sku'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_order_id'), 'purchase_order_lines', ['order_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_product_id'), 'purchase_order_lines', ['product_id'], unique=False)
    op.create_table('order_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['order_email_messages.id'], name=op.f('fk_order_attachments_message_id_order_email_messages')),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], name=op.f('fk_order_attachments_order_id_purchase_orders')),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_order_attachments_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_attachments'))
    )
    op.create_index(op.f('ix_order_attachments_order_id'), 'order_attachments', ['order_id'], unique=False)
    op.create_table('purchase_order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=120), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_purchase_order_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['line_id'], ['purchase_order_lines.id'], name=op.f('fk_purchase_order_events_line_id_purchase_order_lines')),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_events_order_id_purchase_orders')),
    sa.ForeignKeyConstraint(['source_message_id'], ['order_email_messages.id'], name=op.f('fk_purchase_order_events_source_message_id_order_email_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_events'))
    )
    op.create_index(op.f('ix_purchase_order_events_order_id'), 'purchase_order_events', ['order_id'], unique=False)
    op.create_table('order_event_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('parsed_by', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applied_event_id'], ['purchase_order_events.id'], name=op.f('fk_order_event_proposals_applied_event_id_purchase_order_events')),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_order_event_proposals_decided_by_id_users')),
    sa.ForeignKeyConstraint(['line_id'], ['purchase_order_lines.id'], name=op.f('fk_order_event_proposals_line_id_purchase_order_lines')),
    sa.ForeignKeyConstraint(['message_id'], ['order_email_messages.id'], name=op.f('fk_order_event_proposals_message_id_order_email_messages')),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], name=op.f('fk_order_event_proposals_order_id_purchase_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_event_proposals'))
    )
    op.create_index(op.f('ix_order_event_proposals_order_id'), 'order_event_proposals', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_event_proposals_status'), 'order_event_proposals', ['status'], unique=False)
    op.add_column('products', sa.Column('hsn_code', sa.String(length=20), nullable=False, server_default=''))
    op.add_column('products', sa.Column('unit_weight_g', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('target_moh_override', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('moq', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('ordering_exclude', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_products_vendor_id'), 'products', ['vendor_id'], unique=False)
    op.create_foreign_key(op.f('fk_products_vendor_id_vendors'), 'products', 'vendors', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_products_vendor_id_vendors'), 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_vendor_id'), table_name='products')
    op.drop_column('products', 'ordering_exclude')
    op.drop_column('products', 'vendor_id')
    op.drop_column('products', 'moq')
    op.drop_column('products', 'target_moh_override')
    op.drop_column('products', 'unit_weight_g')
    op.drop_column('products', 'hsn_code')
    op.drop_index(op.f('ix_order_event_proposals_status'), table_name='order_event_proposals')
    op.drop_index(op.f('ix_order_event_proposals_order_id'), table_name='order_event_proposals')
    op.drop_table('order_event_proposals')
    op.drop_index(op.f('ix_purchase_order_events_order_id'), table_name='purchase_order_events')
    op.drop_table('purchase_order_events')
    op.drop_index(op.f('ix_order_attachments_order_id'), table_name='order_attachments')
    op.drop_table('order_attachments')
    op.drop_index(op.f('ix_purchase_order_lines_product_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_order_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_global_sku'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_legs_order_id'), table_name='purchase_order_legs')
    op.drop_table('purchase_order_legs')
    op.drop_index(op.f('ix_order_email_messages_order_id'), table_name='order_email_messages')
    op.drop_index(op.f('ix_order_email_messages_message_id'), table_name='order_email_messages')
    op.drop_table('order_email_messages')
    op.drop_table('forecast_analogies')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_status'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_name'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_table('app_settings')
    op.drop_table('vendors')
    # ### end Alembic commands ###
