"""phase3: center/department orders + notification outbox

Additive only (five new tables) — safe on the shared dev database.

Revision ID: b9a08e5413de
Revises: 85a3b2fdc379
Create Date: 2026-07-13 14:40:07.186271
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = 'b9a08e5413de'
down_revision = '85a3b2fdc379'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notify_channel_state',
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('configured', sa.Boolean(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('channel', name=op.f('pk_notify_channel_state'))
    )
    op.create_table('center_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('center_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('reasonability', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reasonability_level', sa.String(length=8), nullable=False),
    sa.Column('picking_status', sa.String(length=12), nullable=False),
    sa.Column('picking_reference', sa.String(length=40), nullable=False),
    sa.Column('picking_error', sa.Text(), nullable=False),
    sa.Column('odoo_picking_id', sa.Integer(), nullable=True),
    sa.Column('odoo_picking_name', sa.String(length=80), nullable=False),
    sa.Column('odoo_picking_url', sa.String(length=500), nullable=False),
    sa.Column('source_location_key', sa.String(length=20), nullable=False),
    sa.Column('picking_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], name=op.f('fk_center_orders_center_id_centers')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_center_orders_created_by_id_users')),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_center_orders_decided_by_id_users')),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['center_orders.id'], name=op.f('fk_center_orders_duplicate_of_id_center_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_center_orders'))
    )
    op.create_index(op.f('ix_center_orders_center_id'), 'center_orders', ['center_id'], unique=False)
    op.create_index(op.f('ix_center_orders_status'), 'center_orders', ['status'], unique=False)
    op.create_table('center_order_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_center_order_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['order_id'], ['center_orders.id'], name=op.f('fk_center_order_events_order_id_center_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_center_order_events'))
    )
    op.create_index(op.f('ix_center_order_events_order_id'), 'center_order_events', ['order_id'], unique=False)
    op.create_table('center_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_requested', sa.Float(), nullable=False),
    sa.Column('qty_approved', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['center_orders.id'], name=op.f('fk_center_order_lines_order_id_center_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_center_order_lines_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_center_order_lines')),
    sa.UniqueConstraint('order_id', 'product_id', name='uq_centerorder_product')
    )
    op.create_index(op.f('ix_center_order_lines_order_id'), 'center_order_lines', ['order_id'], unique=False)
    op.create_index(op.f('ix_center_order_lines_product_id'), 'center_order_lines', ['product_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('to_phone', sa.String(length=40), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('final_channel', sa.String(length=10), nullable=False),
    sa.Column('whatsapp_outcome', sa.String(length=10), nullable=False),
    sa.Column('whatsapp_error', sa.Text(), nullable=False),
    sa.Column('email_outcome', sa.String(length=10), nullable=False),
    sa.Column('email_error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['center_orders.id'], name=op.f('fk_notifications_order_id_center_orders')),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_notifications_recipient_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_kind'), 'notifications', ['kind'], unique=False)
    op.create_index(op.f('ix_notifications_order_id'), 'notifications', ['order_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_order_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_kind'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_center_order_lines_product_id'), table_name='center_order_lines')
    op.drop_index(op.f('ix_center_order_lines_order_id'), table_name='center_order_lines')
    op.drop_table('center_order_lines')
    op.drop_index(op.f('ix_center_order_events_order_id'), table_name='center_order_events')
    op.drop_table('center_order_events')
    op.drop_index(op.f('ix_center_orders_status'), table_name='center_orders')
    op.drop_index(op.f('ix_center_orders_center_id'), table_name='center_orders')
    op.drop_table('center_orders')
    op.drop_table('notify_channel_state')
    # ### end Alembic commands ###
