"""restock reset audit fields

Revision ID: edd20b4b953b
Revises: b9a08e5413de
Create Date: 2026-07-14 15:05:14.900887
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = 'edd20b4b953b'
down_revision = 'b9a08e5413de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restock_fold_state', sa.Column('last_reset_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('restock_fold_state', sa.Column('last_reset_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_restock_fold_state_last_reset_by_id_users'), 'restock_fold_state', 'users', ['last_reset_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_restock_fold_state_last_reset_by_id_users'), 'restock_fold_state', type_='foreignkey')
    op.drop_column('restock_fold_state', 'last_reset_by_id')
    op.drop_column('restock_fold_state', 'last_reset_at')
    # ### end Alembic commands ###
