"""floor oos marks

Revision ID: fbf52b4d8d4c
Revises: edd20b4b953b
Create Date: 2026-07-14 16:02:06.111688
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = 'fbf52b4d8d4c'
down_revision = 'edd20b4b953b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floor_oos_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('qty_removed', sa.Float(), nullable=False),
    sa.Column('picking_status', sa.String(length=12), nullable=False),
    sa.Column('picking_reference', sa.String(length=40), nullable=False),
    sa.Column('picking_error', sa.Text(), nullable=False),
    sa.Column('odoo_picking_id', sa.Integer(), nullable=True),
    sa.Column('odoo_picking_name', sa.String(length=80), nullable=False),
    sa.Column('odoo_picking_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_floor_oos_marks_created_by_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_floor_oos_marks_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_floor_oos_marks'))
    )
    op.create_index(op.f('ix_floor_oos_marks_product_id'), 'floor_oos_marks', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_floor_oos_marks_product_id'), table_name='floor_oos_marks')
    op.drop_table('floor_oos_marks')
    # ### end Alembic commands ###
